export const DEFAULT_GIFTS: { name: string; category: string }[] = [
  { name: "Pañales talle recién nacido", category: "Higiene" },
  { name: "Pañales talle 1", category: "Higiene" },
  { name: "Toallitas húmedas", category: "Higiene" },
  { name: "Crema para la cola", category: "Higiene" },
  { name: "Jabón / shampoo neutro", category: "Higiene" },
  { name: "Bodies (varios talles)", category: "Ropa" },
  { name: "Conjuntos de ropa", category: "Ropa" },
  { name: "Medias y escarpines", category: "Ropa" },
  { name: "Gorritos", category: "Ropa" },
  { name: "Baberos", category: "Ropa" },
  { name: "Mamaderas", category: "Alimentación" },
  { name: "Chupetes", category: "Alimentación" },
  { name: "Extractor de leche", category: "Alimentación" },
  { name: "Sábanas para la cuna", category: "Habitación" },
  { name: "Móvil musical", category: "Habitación" },
  { name: "Luz de noche", category: "Habitación" },
  { name: "Termómetro ambiente", category: "Habitación" },
  { name: "Cochecito", category: "Paseo" },
  { name: "Bolso maternal", category: "Paseo" },
  { name: "Mochila portabebé", category: "Paseo" },
  { name: "Manta para upa", category: "Otros" },
  { name: "Libros de tela / sonajeros", category: "Otros" },
];
